const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const BugSchema = new Schema({
    "Product":{
        type:String,
        required:true
    },
    "Component":{
        type:String,
        required:true
    },
    "Assignee":{
        type:String,
        required:true
    },
    "Status": {
        type:String
    },
    "Resolution":{
        type:String
    },
    "Summary":{
        type:String,
        required:true
    },
    "Changed":{
        type:String,
    },
    "AssigneeRealName":{
        type:String,
    },
    "Classification":{
        type:String,
    },
    "Flags":{
        type:String,
    },
    "Hardware":{
        type:String,
        required:true
    },
    "Keywords":{
        type:String,
    },
    "Opened":{
        type:Date,
        default:new Date()
    },
    "OS":{
        type:String,
        required:true
    },
    "Priority":{
        type:String,
        required:true
    },
    "QAContact":{
        type:String,
    },
    "QAContactRealName":{
        type:String,
    },
    "Reporter":{
        type:String,
        required:true
    },
    "Severity":{
        type:String,
        required:true
    },
    "Summary__1":{
        type:String,
    },
    "Tags":{
        type:String,
    },
    "TargetMilestone":{
        type:String,
    },
    "URL":{
        type:String,
    },
    "Version":{
        type:String,
    },
    "Votes":{
        type:Number,
        default:0
    },
    "Whiteboard":{
        type:String,
    },
    "Alias":{
        type:String,
    },
    "Comments":{
        type:Array,
        default:[]
    }
})

module.exports = mongoose.model("Bugs",BugSchema);